version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Install tools
          command: |
            sudo apt update
            sudo apt install -y nodejs npm
            sudo npm install n -g
            sudo n stable
            sudo apt purge -y nodejs npm
      - run:
          name: Build Frontend Application
          working_directory: src/frontend
          command: |
            npm install
            npm run build
            cp -rp build /tmp/build
      - run:
          name: Start containers
          working_directory: docker/prod
          command: |
            set -x
      - run:
          name: Integration test - Access landing page
          command: |
            for i in {0..10}; do
              STATUS_CODE=$(curl -LI http://localhost -o /dev/null -w '%{http_code}\n' -s)
              [[ $STATUS_CODE == '200' ]] && exit 0 
              sleep 3
            done
            exit 1
  push_image:
    machine:
      image: ubuntu-2204:current
    environment:
      - IMAGE: 'tuimac/fileserver'
      - DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - checkout
      - run:
          name: Login Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Setup Docker Buildx
          command: |
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker context create circleci
            docker buildx create --use circleci
      - run:
          name: Build and Push docker image
          command: |
            docker buildx build --push --platform linux/ppc64le,linux/s390x,linux/arm64,linux/amd64 -t ${IMAGE} .
workflows:
  version: 2.1
  pipeline:
    jobs:
      - build:
      - push_image:
          requires:
            - build
